site:
  title: Agentic Dev Stacks
  start_page: agentic-dev-stacks::index.adoc

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: docs
      edit_url: https://github.com/n00tropic/agentic-dev-stacks/edit/{refname}/{path}

runtime:
  fetch: false

asciidoc:
  attributes:
    sectanchors: ""
    sectnums: ""
    source-highlighter: highlightjs
    kroki-fetch-diagram!:
  extensions:
    - asciidoctor-kroki

output:
  dir: build/site

ui:
  bundle:
    url: ./ui/agentic-neon-ui/build/ui-bundle.zip
    snapshot: true
